-- Create marker_logs table for tracking add/delete operations
create table if not exists marker_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  group_id text,
  marker_name text,
  description text,
  operation_type text, -- 'add' or 'delete'
  dataset_group text -- optional, for multi-tenant or dataset separation
);

-- Enable RLS (Row Level Security)
alter table marker_logs enable row level security;

-- Create policy to allow all users to insert logs
create policy "Enable insert for all users"
on marker_logs for insert
with check (true);

-- Create policy to allow all users to view logs (optional, depending on needs)
create policy "Enable select for all users"
on marker_logs for select
using (true);
